name: avm_required
description: AVM minimum required branch protection policy
resource: repository
where:
configuration:
  branchProtectionRules:
    - branchNamePattern: "~default~"
      requiresPullRequestBeforeMerging: true
      requiredApprovingReviewsCount: 1
      isAdminEnforced: true
      allowsForcePushes: false
      allowsDeletions: false
      requiresLinearHistory: true
      requireCodeOwnersReview: true
      dismissStaleReviews: true
      requireLastPushApproval: true
